# Generated by Django 5.1.4 on 2024-12-07 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCloth',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_table',
            },
        ),
        migrations.CreateModel(
            name='CategoryUser',
            fields=[
                ('categoryUser_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryUser_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_user_table',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('cloth_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='clothes_images/')),
                ('stock', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorycloth')),
            ],
            options={
                'db_table': 'cloth_table',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('categoryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categoryuser')),
            ],
            options={
                'db_table': 'register_table',
            },
        ),
    ]
