# Generated by Django 5.1.4 on 2024-12-10 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_categorygender_categorycloth_category_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycloth',
            old_name='category_name',
            new_name='CategoryCloth_name',
        ),
        migrations.RenameField(
            model_name='categorycloth',
            old_name='category_id',
            new_name='categoryCloth_id',
        ),
        migrations.RemoveField(
            model_name='categorycloth',
            name='category_gender',
        ),
        migrations.AlterModelTable(
            name='categorycloth',
            table='category_cloth_table',
        ),
        migrations.CreateModel(
            name='SubCategoryCloth',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(max_length=255)),
                ('category_gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorygender')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorycloth')),
            ],
            options={
                'db_table': 'sub_category_table',
            },
        ),
    ]
