# Generated by Django 5.1.4 on 2024-12-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_rename_category_name_categorycloth_categorycloth_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.subcategorycloth'),
        ),
    ]
