# Generated by Django 5.1.4 on 2024-12-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_clothes_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.register')),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
    ]
