# Generated by Django 5.1.4 on 2024-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0007_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sizes_table',
            },
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ManyToManyField(to='Adminapp.sizes'),
        ),
    ]
