# Generated by Django 5.1.4 on 2024-12-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0008_sizes_clothes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycloth',
            name='categoryGender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.categorygender'),
        ),
    ]
