# Generated by Django 5.1.4 on 2024-12-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_categorycloth_categorygender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycloth',
            name='categoryGender',
        ),
        migrations.AddField(
            model_name='categorycloth',
            name='categoryGender',
            field=models.ManyToManyField(to='Adminapp.categorygender'),
        ),
    ]
