# Generated by Django 5.1.4 on 2024-12-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0010_remove_categorycloth_categorygender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorycloth',
            name='category_gender',
        ),
    ]
