# Generated by Django 5.1.4 on 2024-12-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0012_sizenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='sizeNumber',
            field=models.ManyToManyField(to='Adminapp.sizenumber'),
        ),
    ]
