# Generated by Django 5.1.4 on 2024-12-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0014_remove_clothes_sizenumber_delete_sizenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.register'),
        ),
    ]
